pipeline:
  build:
    image: rust
    commands:
      - cargo build --locked
  test:
    image: rust
    commands:
      - cargo test --locked
      - cargo test --locked --all-features
  lint:
    image: rust
    commands:
      - rustup component add rustfmt clippy
      - cargo fmt -- --check --files-with-diff
      - cargo clippy --no-deps
  msrv:
    image: rust:1.64
    commands:
      - cargo build --locked
