pipeline:
  build:
    image: rust
    commands:
      - cargo build --locked
  test:
    image: rust
    commands:
      - cargo test
      - cargo test --all-features
  lint:
    image: rustdocker/rustfmt_clippy:nightly
    commands:
      - cargo fmt -- --check --files-with-diff
      - cargo clippy --no-deps
  msrv:
    image: rust:1.60
    commands:
      - cargo build --locked
