pipeline:
  build:
    image: rust:1.58
    commands:
      - cargo build
  test:
    image: rust:1.58
    commands:
      - cargo test --all-features
  lint:
    image: rust:1.58
    commands:
      - rustup component add rustfmt clippy
      - cargo fmt -- --check --files-with-diff
      - cargo clippy --no-deps
