pipeline:
  build:
    image: rust:1.58
    commands:
      - cargo build
  test:
    image: rust:1.58
    commands:
      - cargo test
      - cargo test --all-features
  lint:
    image: rustdocker/rustfmt_clippy:nightly
    commands:
      - cargo fmt -- --check --files-with-diff
      - cargo clippy --no-deps
