pipeline:
  build:
    image: rust
    commands:
      - cargo build --locked
  test:
    image: rust
    commands:
      - cargo test --locked
      - cargo test --locked --all-features
  lint:
    image: rustdocker/rustfmt_clippy:nightly
    commands:
      - rustfmt -- --check --files-with-diff
      - cargo-clippy --no-deps
  msrv:
    image: rust:1.60
    commands:
      - cargo build --locked
