[package]
name = "imdb-id"
description = "Get IMDb IDs using a commandline search tool"
categories = ["command-line-utilities"]
version = "0.1.0"
edition = "2018"
authors = ["alpha-tango-kilo <git@heyatk.com>"]
readme = "README.md"
license = "GPL-3.0-only"
homepage = "https://codeberg.org/alpha-tango-kilo/imdb-id"
repository = "https://codeberg.org/alpha-tango-kilo/imdb-id"

[dependencies]
anyhow = "1.0"
lazy-regex = "2.2"
scraper = "0.12"

[dependencies.reqwest]
version = "0.11"
features = [
    "blocking",
]
