[package]
name = "imdb-id"
description = "Get IMDb IDs using a commandline search tool"
categories = ["command-line-utilities"]
version = "1.0.5"
edition = "2018"
authors = ["alpha-tango-kilo <git@heyatk.com>"]
readme = "README.md"
license = "GPL-3.0-only"
homepage = "https://codeberg.org/alpha-tango-kilo/imdb-id"
repository = "https://codeberg.org/alpha-tango-kilo/imdb-id"

[dependencies]
atty = "0.2"
crossterm = "0.20"
lazy-regex = "2.2"
scraper = "0.12"
requestty = "0.1"
serde_json = { version = "1.0", optional = true }
serde_yaml = { version = "0.8", optional = true }

[dependencies.clap]
version = "3.0.0-beta.2"
default-features = false
features = [
    "std",
    "color",
]

[dependencies.reqwest]
version = "0.11"
features = [
    "blocking",
]

[dependencies.serde]
version = "1.0"
optional = true
features = [
    "derive",
]

[features]
json = ["serde", "serde_json"]
yaml = ["serde", "serde_yaml"]

[profile.release]
lto = true
